# config/routes.yaml

# Load all controllers using PHP 8 attributes
controllers:
    resource: ../src/Controller/
    type: attribute
    
# api_token_refresh:
#     path: /api/token/refresh
#     controller: gesdinet.jwtrefreshtoken::refresh